---
json_rpc_url: "https://api.devnet.solana.com"
websocket_url: ""
keypair_path: /Users/z/.config/solana/id.json
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
